### ISSUE TITLE
How to print attributes

### ISSUE THREAD

**Issue by aEileen** [FacePlusPlus/python-sdk#3]
api.detect(image_file = File(r'demo.jpeg')); 
I want to print those attributes, like age etc. then I try:
api.detect(image_file = File(r'demo.jpeg'), attribute = "gender"); 

There is no error, but also no attributes.
Why? How do I print the attributes?

**Comment by FMCumhaill** [comment]
It should be 
`api.detect(image_file = File(r'./demo.jpeg'),return_attributes='gender')`

@aEileen  perhaps you can close the issue?
